### ISSUE TITLE
Création de lien pour appeler directement un # de téléphone

### ISSUE THREAD

**Issue by qwertyuu** [qwertyuu/quebec-achat-local#5]
J'ai trouvé [cette librairie](http://greg-jacobs.com/Autolinker.js/examples/index.html) qui pourrait être rapidement ajoutée afin de générer des liens cliquables depuis le contenu affiché dans la page, pour permettre aux gens d'appeler directement depuis leur cellulaires s'ils sont sur mobile par exemple

On pourrais seulement utiliser `phone: true` comme option, car la librairie supporte plus d'entités différentes que le # de téléphone mais on en a pas besoin

Dépend de #3

**Comment by etiennellipse** [comment]
Ça me semblerait plus simple d'avoir un champ # téléphone dans le modèle de données pour ça. Après, faire un lien avec pour appeler c'est simpletto: 
```
<a href="tel:555-5555">555-5555</a>
```

**Comment by qwertyuu** [comment]
C'est vrai!
