### ISSUE TITLE
Certificat SSL

### ISSUE THREAD

**Issue by qwertyuu** [qwertyuu/quebec-achat-local#6]
Pour le moment je suis sur Heroku, et j'ai pour but de ne pas payer les infrastructures utilisées pour le projet, afin de démontrer que tout ça est possible avec le communautaire.
J'ai besoin d'aide pour installer un certificat SSL et rendre le site plus sur, même si je sais que c'est pas nécessaire ici. Ça rendrait la population plus sécure.

**Comment by GabLeRoux** [comment]
Il existe plusieurs options. Celles que je vois accessibles rapidement:

1. Utiliser Cloudflare avec Heroku pour obtenir une terminaison SSL. Voir guide suivant: https://support.cloudflare.com/hc/en-us/articles/205893698
2. Héberger la partie exposée au client de manière statique sur [Github Pages](https://pages.github.com/) (ou autre service similaire comme [Gitlab Pages]())
3. Passer à du self-hosted et utiliser un outil comme [herokuish](https://github.com/gliderlabs/herokuish) pour le déploiement et utiliser [LetsEncrypt](https://letsencrypt.org/) devant le service (ou même [Caddy Server](https://caddyserver.com/) qui peut gérer le tout automatiquement)

Selon moi, l'option 1 (cloudflare + Heroku) est la plus simple en ce moment et ce qui est bien avec cette option, c'est qu'elle peut continuer de fonctionner avec d'autres solutions d'hébergement plus tard.

**Comment by qwertyuu** [comment]
@GabLeRoux T'es mon préféré. J'ai réussi avec la technique 1.

NOUVEL URL OFFICIELLE: https://achetelocal.com

**Comment by GabLeRoux** [comment]
Toi t'es mon préféré #bromance
![so proud](https://media.giphy.com/media/dvg444bbObjHMg87sm/giphy-downsized.gif)
